Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: slashes

  SupportedStyles:
    - slashes
    - percent_r
    - mixed

  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Lint/ImplicitStringConcatenation:
  Enabled: false

Security/Eval:
  Description: 'The use of eval represents a serious security risk.'
  Enabled: false

AllCops:
  Exclude:
    - 'compiled_lisp.rb'

