Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: slashes

  SupportedStyles:
    - slashes
    - percent_r
    - mixed

  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false